### ISSUE TITLE
Header issue when installed through nimble

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-rocksdb#3] opened 2018-07-04 10:10 UTC
When doing `nimble test` from Nimbus on mac I get the following:

```
/Users/.../Programming/Status/nimbus/nimcache/nimbus_rocksdb_backend.c:12:10: fatal error: '/Users/.../.nimble/pkgs/headers/c.h' file not found
#include "/Users/.../.nimble/pkgs/headers/c.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

which comes from https://github.com/status-im/nim-rocksdb/blob/92ac374a55ca822131a3c6a8bc05c53bb638f69d/src/rocksdb/librocksdb.nim#L38-L40

So:

1. headers should be added in the nimble file
2. The path resolution is wrong, it should be something like: `~/.nimble/pkgs/rocksdb-0.2.0/rocksdb/headers/c.h`

Cloning rocksdb locally and using `nimble develop` instead of `nimble install` works fine however.

Given how nimble works, the package structure should be changed from

`project/src/<files>`

to

`project/nimblename/<files>`

because on nimble install the "src" directory disappears and we can't rely on paths.

**Comment by zah** [comment] 2018-07-04 10:53
An alternative solution would be to move the `headers` folder inside the `src` folder. It seems that the problem is that nimble deploys only the `src` folder on installations.

**Comment by mratsim** [comment] 2018-07-04 10:55
Yes this is my point 1, but beyond that nimble is checking the wrong place `/Users/.../.nimble/pkgs/headers/c.h` instead of `~/.nimble/pkgs/rocksdb-0.2.0/rocksdb/headers/c.h` (which I agree would require installing both the `src` and the `headers` directories)

**Comment by yglukhov** [comment] 2018-07-05 07:46
Fixed by changing pkg structure.

**Closed as completed by yglukhov** 2018-07-05 07:46 UTC
Labels: build, nimble
